nhnacademy-be7-55G-COM/55G.COM-shop

- src/main/resources/application.properties
- src/main/resources/application.yml
> Feat: dev profile & port

- Dockerfile
- pom.xml
- startup.sh
> Feat: 도커 이미지 자동 빌드 스크립트

- .github/workflows/maven.yml
> Feat: Continuous destribution

- pom.xml
- src/main/resources/application.yml
- startup.sh
> Fix: Docker image

- src/main/java/shop/S5G/shop/ShopApplication.java
> Fix: Bean 인식 불가 문제 해결

- src/main/java/shop/S5G/shop/entity/Delivery.java
- src/main/java/shop/S5G/shop/entity/DeliveryFee.java
- src/main/java/shop/S5G/shop/entity/Order.java
- src/main/java/shop/S5G/shop/entity/OrderDetail.java
- src/main/java/shop/S5G/shop/entity/OrderDetailType.java
- src/main/java/shop/S5G/shop/entity/RefundHistory.java
- src/main/java/shop/S5G/shop/entity/RefundImage.java
- src/main/java/shop/S5G/shop/entity/RefundType.java
- src/main/java/shop/S5G/shop/entity/WrappingPaper.java
- src/main/java/shop/S5G/shop/entity/order/Delivery.java
- src/main/java/shop/S5G/shop/entity/order/DeliveryFee.java
- src/main/java/shop/S5G/shop/entity/order/Order.java
- src/main/java/shop/S5G/shop/entity/order/OrderDetail.java
- src/main/java/shop/S5G/shop/entity/order/OrderDetailType.java
- src/main/java/shop/S5G/shop/entity/order/RefundHistory.java
- src/main/java/shop/S5G/shop/entity/order/RefundImage.java
- src/main/java/shop/S5G/shop/entity/order/RefundType.java
- src/main/java/shop/S5G/shop/entity/order/WrappingPaper.java
- src/main/java/shop/S5G/shop/repository/order/DeliveryFeeRepository.java
- src/main/java/shop/S5G/shop/repository/order/DeliveryRepository.java
- src/main/java/shop/S5G/shop/repository/order/OrderDetailRepository.java
- src/main/java/shop/S5G/shop/repository/order/OrderDetailTypeRepository.java
- src/main/java/shop/S5G/shop/repository/order/OrderRepository.java
- src/main/java/shop/S5G/shop/repository/order/RefundHistoryRepository.java
- src/main/java/shop/S5G/shop/repository/order/RefundImageRepository.java
- src/main/java/shop/S5G/shop/repository/order/RefundTypeRepository.java
- src/main/java/shop/S5G/shop/repository/order/WrappingPaperRepository.java
> Feat: [주문/결제] Entity, Repository 생성

- pom.xml
- src/main/java/shop/S5G/shop/repository/cart/CartRedisRepository.java
- src/main/java/shop/S5G/shop/service/CartService.java
- src/test/java/shop/S5G/shop/controller/CartControllerTest.java
- src/test/java/shop/S5G/shop/repository/RedisRepositoryTest.java
- src/test/java/shop/S5G/shop/service/CartServiceTest.java
Create CartService, CartRedisRepository test code
> test: "Create CartService, CartRedisRepository test code"

- src/main/resources/application.yml
> Fix: properties mysql 수정

- .github/workflows/maven.yml
RedisConnectionFactory가 github actions에서 작동하는 문제를 수정
> Feat: Disable RedisConfig when github actions build

- http/coupon/policy.http
- http/coupon/template.http
- pom.xml
- src/main/java/shop/S5G/shop/controller/coupon/CouponTemplateController.java
- src/main/java/shop/S5G/shop/dto/coupon/template/CouponTemplateRequestDto.java
- src/main/java/shop/S5G/shop/entity/coupon/CouponTemplate.java
- src/main/java/shop/S5G/shop/exception/coupon/CouponTemplateBadRequestException.java
- src/main/java/shop/S5G/shop/exception/coupon/CouponTemplateNotFoundException.java
- src/main/java/shop/S5G/shop/repository/coupon/template/CouponTemplateRepository.java
- src/main/java/shop/S5G/shop/repository/coupon/template/qdsl/CouponTemplateQuerydslRepository.java
- src/main/java/shop/S5G/shop/repository/coupon/template/qdsl/CouponTemplateQuerydslRepositoryImpl.java
- src/main/java/shop/S5G/shop/service/coupon/template/CouponTemplateService.java
- src/main/java/shop/S5G/shop/service/coupon/template/impl/CouponTemplateServiceImpl.java
- src/test/java/shop/S5G/shop/controller/coupon/policy/CouponPolicyControllerTest.java
- src/test/java/shop/S5G/shop/controller/coupon/policy/CouponPolicyExceptionTest.java
- src/test/java/shop/S5G/shop/controller/coupon/template/CouponTemplateControllerTest.java
- src/test/java/shop/S5G/shop/controller/coupon/template/CouponTemplateExceptionTest.java
- src/test/java/shop/S5G/shop/repository/coupontemplate/CouponTemplateRepositoryTest.java
- src/test/java/shop/S5G/shop/service/coponpolicy/impl/CouponPolicyServiceExceptionTest.java
- src/test/java/shop/S5G/shop/service/coupontemplate/CouponTemplateServiceExceptionTest.java
- src/test/java/shop/S5G/shop/service/coupontemplate/CouponTemplateServiceImplTest.java
Repository Querydsl을 이용하여 구현
Service 구현
Controller 구현
> Feat: 쿠폰 템플릿 CRUD 구현

- src/main/java/shop/S5G/shop/actuator/ApplicationStatus.java
- src/main/java/shop/S5G/shop/actuator/CustomHealthIndicator.java
- src/main/java/shop/S5G/shop/controller/ApplicationStatusController.java
- src/main/resources/application.yml
- startup.sh
인스턴스 상태를 변경하는 컨트롤러 추가
컨테이너 삭제 후 새롭게 생성될 때까지 대기하게 한 후 다음 컨테이너 로직 처리
> Feat: 무중단 배포

- startup.sh
> Fix: shell script 수정 final final

- pom.xml
- src/main/resources/application.yml
> Feat: dbcp 설정

- http/member/member.http
- pom.xml
- src/main/java/shop/S5G/shop/exception/AuthenticationException.java
- src/main/java/shop/S5G/shop/util/JwtUtil.java
> Feat: jwt util 구현

- .github/workflows/maven.yml
> Fix: Resolve jacoco problem

- pom.xml
- src/main/java/shop/S5G/shop/config/SecurityConfig.java
- src/main/java/shop/S5G/shop/controller/TestController.java
- src/main/java/shop/S5G/shop/entity/order/Delivery.java
- src/main/java/shop/S5G/shop/filter/JwtAuthenticationFilter.java
- src/main/java/shop/S5G/shop/security/ShopMemberDetail.java
- src/main/java/shop/S5G/shop/util/JwtUtil.java
- src/main/resources/application.yml
- src/test/java/shop/S5G/shop/annotation/WithCustomMockUser.java
- src/test/java/shop/S5G/shop/config/TestSecurityConfig.java
- src/test/java/shop/S5G/shop/config/WithCustomMockUserSecurityContextFactory.java
- src/test/java/shop/S5G/shop/controller/book/BookCategoryControllerTest.java
- src/test/java/shop/S5G/shop/controller/book/BookControllerTest.java
- src/test/java/shop/S5G/shop/controller/cart/CartControllerTest.java
- src/test/java/shop/S5G/shop/controller/coupon/policy/CouponPolicyControllerTest.java
- src/test/java/shop/S5G/shop/controller/coupon/policy/CouponPolicyExceptionTest.java
- src/test/java/shop/S5G/shop/controller/coupon/template/CouponTemplateControllerTest.java
- src/test/java/shop/S5G/shop/controller/coupon/template/CouponTemplateExceptionTest.java
- src/test/java/shop/S5G/shop/controller/member/MemberControllerTest.java
- src/test/java/shop/S5G/shop/controller/member/MemberGradeControllerTest.java
- src/test/java/shop/S5G/shop/controller/member/MemberStatusControllerTest.java
- src/test/java/shop/S5G/shop/controller/order/OrderControllerTest.java
- src/test/java/shop/S5G/shop/controller/order/OrderDetailControllerTest.java
- src/test/java/shop/S5G/shop/controller/publisher/PublisherControllerTest.java
- src/test/java/shop/S5G/shop/controller/tag/TagControllerTest.java
- src/test/java/shop/S5G/shop/repository/book/BookCategoryRepositoryTest.java
- src/test/java/shop/S5G/shop/test/SecurityTest.java
1. 멤버 정보 가져오기
2. 배송정보 업데이트 가능
컨트롤러 테스트에 이거 붙여주세요
```java
@WebMvcTest(
value = Controller.class,
excludeFilters = @ComponentScan.Filter(
type= FilterType.ASSIGNABLE_TYPE,
classes = {SecurityConfig.class, JwtAuthenticationFilter.class}
)
)
@Import(TestSecurityConfig.class)
```
> Feat: spring security

- .github/workflows/maven.yml
> Fix: master 브랜치에 반응하지 않도록 변경

- src/main/java/shop/s5g/shop/controller/book/BookController.java
- src/main/java/shop/s5g/shop/controller/book/CategoryController.java
- src/main/java/shop/s5g/shop/controller/publisher/PublisherController.java
- src/main/java/shop/s5g/shop/dto/book/BookPageableResponseDto.java
- src/main/java/shop/s5g/shop/dto/category/CategoryResponseDto.java
- src/main/java/shop/s5g/shop/dto/publisher/PublisherRequestDto.java
- src/main/java/shop/s5g/shop/dto/publisher/PublisherResponseDto.java
- src/main/java/shop/s5g/shop/entity/BookImage.java
- src/main/java/shop/s5g/shop/repository/book/qdsl/impl/BookQuerydslRepositoryImpl.java
- src/main/java/shop/s5g/shop/repository/bookstatus/qdsl/impl/BookStatusQuerydslRepositoryImpl.java
- src/main/java/shop/s5g/shop/repository/category/qdsl/CategoryQuerydslRepository.java
- src/main/java/shop/s5g/shop/repository/category/qdsl/impl/CategoryQuerydslRepositoryImpl.java
- src/main/java/shop/s5g/shop/repository/publisher/qdsl/PublisherQuerydslRepository.java
- src/main/java/shop/s5g/shop/repository/publisher/qdsl/impl/PublisherQuerydslRepositoryImpl.java
- src/main/java/shop/s5g/shop/service/book/impl/BookServiceImpl.java
- src/main/java/shop/s5g/shop/service/category/CategoryService.java
- src/main/java/shop/s5g/shop/service/category/impl/CategoryServiceImpl.java
- src/main/java/shop/s5g/shop/service/publisher/PublisherService.java
- src/main/java/shop/s5g/shop/service/publisher/impl/PublisherServiceImpl.java
- src/main/resources/application.yml
- src/test/java/shop/s5g/shop/controller/book/BookControllerTest.java
- src/test/java/shop/s5g/shop/controller/coupon/coupon/CouponControllerTest.java
- src/test/java/shop/s5g/shop/repository/book/BookRepositoryTest.java
- src/test/java/shop/s5g/shop/repository/publisher/PublisherRepositoryTest.java
- src/test/java/shop/s5g/shop/service/publisher/PublisherServiceTest.java
- 도서 전체 조회 pageable
- 자식 카테고리 조회 기능
- 국내도서 하위 카테고리 조회 기능
> Fix: 도서 전체 조회 pageable 추가

- .github/workflows/maven.yml
- src/main/java/shop/s5g/shop/config/ElasticSearchConfig.java
- src/main/java/shop/s5g/shop/controller/book/BookDocumentController.java
- src/main/java/shop/s5g/shop/entity/document/BookDocument.java
- src/main/java/shop/s5g/shop/repository/book/BookDocumentRepository.java
- src/main/java/shop/s5g/shop/service/book/BookDocumentService.java
- src/main/java/shop/s5g/shop/service/book/impl/BookDocumentServiceImpl.java
- src/main/resources/application.yml
- 검색어는 제목(title)과 설명(description)에 포함되면 조회됨
> Feat: 엘라스틱서치에서 검색어에 해당하는 도서 리스트 조회하는 기능

- src/main/java/shop/s5g/shop/controller/book/BookDocumentController.java
- src/main/java/shop/s5g/shop/dto/book/BookDocumentResponseDto.java
- src/main/java/shop/s5g/shop/entity/document/BookDocument.java
- src/main/java/shop/s5g/shop/service/book/BookDocumentService.java
- src/main/java/shop/s5g/shop/service/book/impl/BookDocumentServiceImpl.java
- 메서드명 수정
- 필요없는 dto 필드 제거
- 필요한 dto, document 필드 추가
- 검색되는 필드와 가중치 추가
> Feat: 제목, 설명, 태그, 작가, 출판사로 검색 & dto, document 필드 변경

- src/main/java/shop/s5g/shop/controller/author/AuthorController.java
- src/main/java/shop/s5g/shop/controller/book/BookController.java
- src/main/java/shop/s5g/shop/controller/book/CategoryController.java
- src/main/java/shop/s5g/shop/dto/author/AllAuthorResponseDto.java
- src/main/java/shop/s5g/shop/dto/author/AuthorRequestDto.java
- src/main/java/shop/s5g/shop/entity/Author.java
- src/main/java/shop/s5g/shop/exception/author/AuthorAlreadyExistsException.java
- src/main/java/shop/s5g/shop/exception/author/AuthorBadRequestException.java
- src/main/java/shop/s5g/shop/exception/author/AuthorResourceNotFooundException.java
- src/main/java/shop/s5g/shop/repository/author/AuthorRepository.java
- src/main/java/shop/s5g/shop/repository/author/qdsl/AuthorQuerydslRepository.java
- src/main/java/shop/s5g/shop/repository/author/qdsl/impl/AuthorQuerydslRepositoryImpl.java
- src/main/java/shop/s5g/shop/service/author/AuthorService.java
- src/main/java/shop/s5g/shop/service/author/impl/AuthorServiceImpl.java
- src/main/java/shop/s5g/shop/service/book/BookService.java
- src/main/java/shop/s5g/shop/service/book/impl/BookServiceImpl.java
- src/main/java/shop/s5g/shop/service/tag/TagService.java
- 작가 등록, 조회
- 카테고리 삭제 오류 수정
- 디자인 수정
> Feat : 작가 등록, 조회, 카테고리 삭제 오류 수정

- pom.xml
- src/main/java/shop/s5g/shop/controller/refund/RefundController.java
- src/main/java/shop/s5g/shop/dto/refund/OrderDetailDeliveryPairContainer.java
- src/main/java/shop/s5g/shop/dto/refund/RefundHistoryCreateRequestDto.java
- src/main/java/shop/s5g/shop/dto/refund/RefundHistoryCreateResponseDto.java
- src/main/java/shop/s5g/shop/entity/refund/RefundHistory.java
- src/main/java/shop/s5g/shop/entity/refund/RefundImage.java
- src/main/java/shop/s5g/shop/entity/refund/RefundType.java
- src/main/java/shop/s5g/shop/exception/refund/RefundAlreadyProceedException.java
- src/main/java/shop/s5g/shop/exception/refund/RefundConditionNotFulfilledException.java
- src/main/java/shop/s5g/shop/repository/order/RefundTypeRepository.java
- src/main/java/shop/s5g/shop/repository/order/qdsl/OrderDetailQuerydslRepository.java
- src/main/java/shop/s5g/shop/repository/order/qdsl/impl/OrderDetailQuerydslRepositoryImpl.java
- src/main/java/shop/s5g/shop/repository/order/qdsl/impl/RefundHistoryQuerydslRepositoryImpl.java
- src/main/java/shop/s5g/shop/service/order/RefundHistoryService.java
- src/main/java/shop/s5g/shop/service/order/impl/RefundHistoryServiceImpl.java
- src/test/java/shop/s5g/shop/service/order/RefundHistoryServiceImplTest.java
[Feat: 반품(환불) 기능 #137](https://github.com/nhnacademy-be7-55G-COM/55G.COM-front/pull/137)
같이 체크해주세요
> Feat: 반품(환불) 기능

- src/main/java/shop/s5g/shop/controller/author/AuthorController.java
- src/main/java/shop/s5g/shop/controller/book/BookCategoryController.java
- src/main/java/shop/s5g/shop/controller/book/BookTagController.java
- src/main/java/shop/s5g/shop/controller/book/LikeController.java
- src/main/java/shop/s5g/shop/dto/author/AuthorResponseDto.java
- src/main/java/shop/s5g/shop/entity/Category.java
- src/main/java/shop/s5g/shop/entity/Like.java
- src/main/java/shop/s5g/shop/entity/like/Like.java
- src/main/java/shop/s5g/shop/entity/like/LikeId.java
- src/main/java/shop/s5g/shop/repository/author/qdsl/AuthorQuerydslRepository.java
- src/main/java/shop/s5g/shop/repository/author/qdsl/impl/AuthorQuerydslRepositoryImpl.java
- src/main/java/shop/s5g/shop/repository/book/category/qdsl/impl/BookCategoryQuerydslRepositoryImpl.java
- src/main/java/shop/s5g/shop/repository/publisher/qdsl/PublisherQuerydslRepository.java
- src/main/java/shop/s5g/shop/repository/publisher/qdsl/impl/PublisherQuerydslRepositoryImpl.java
- src/main/java/shop/s5g/shop/service/author/AuthorService.java
- src/main/java/shop/s5g/shop/service/author/impl/AuthorServiceImpl.java
- src/main/java/shop/s5g/shop/service/booktag/BookTagService.java
- src/main/java/shop/s5g/shop/service/booktag/impl/BookTagServiceImpl.java
- src/main/java/shop/s5g/shop/service/category/impl/CategoryServiceImpl.java
- src/main/java/shop/s5g/shop/service/tag/impl/TagServiceImpl.java
> Fix : 동작오류 해결

- src/main/java/shop/s5g/shop/controller/order/OrderDetailController.java
- src/main/java/shop/s5g/shop/dto/order/DetailStatusChangeRequestDto.java
- src/main/java/shop/s5g/shop/dto/order/OrderDetailInfoDto.java
- src/main/java/shop/s5g/shop/service/order/OrderDetailService.java
- src/main/java/shop/s5g/shop/service/order/OrderService.java
- src/main/java/shop/s5g/shop/service/order/impl/OrderDetailServiceImpl.java
- src/main/java/shop/s5g/shop/service/order/impl/OrderServiceImpl.java
- src/test/java/shop/s5g/shop/controller/order/OrderDetailControllerTest.java
현재 비회원 주문조회 막아놓음
Footer: 전체적으로 리소스 권한관리를 해야함.
> Feat: 주문 확정 기능

- .github/workflows/maven.yml
> Actions workflow 테스트용 PR

- src/main/java/shop/s5g/shop/dto/order/OrderCreateResponseDto.java
- src/test/java/shop/s5g/shop/controller/order/OrderControllerTest.java
https://github.com/nhnacademy-be7-55G-COM/55G.COM-front/pull/165
> Fix: 주문 조회 핫픽스

- src/main/java/shop/s5g/shop/adapter/ImageProviderAdapter.java
- src/main/java/shop/s5g/shop/config/ComponentBuilderConfig.java
- src/main/java/shop/s5g/shop/config/FeignImageProviderAuthorizationConfig.java
- src/main/java/shop/s5g/shop/controller/review/ReviewController.java
- src/main/java/shop/s5g/shop/dto/image/ImageResponseDto.java
- src/main/java/shop/s5g/shop/dto/review/CreateReviewRequestDto.java
- src/main/java/shop/s5g/shop/dto/review/UpdateReviewRequestDto.java
- src/main/java/shop/s5g/shop/entity/review/Review.java
- src/main/java/shop/s5g/shop/exception/review/ReviewNotFoundException.java
- src/main/java/shop/s5g/shop/repository/review/ReviewImageRepository.java
- src/main/java/shop/s5g/shop/service/image/ImageService.java
- src/main/java/shop/s5g/shop/service/image/impl/ImageServiceImpl.java
- src/main/java/shop/s5g/shop/service/review/ReviewService.java
- src/main/java/shop/s5g/shop/service/review/impl/ReviewServiceImpl.java
- src/main/resources/application.yml
- nhn cloud에 image를 저장하는 코드를 shop에 추가
- 리뷰 등록할 때 front server에서 이미지 처리하던 부분을 shop에서 처리
> Feat: 리뷰 수정(이미지 제외)
